export const ADMIN_LOGIN = "ADMIN_LOGIN"
export const ADMIN_LOGOUT = "ADMIN_LOGOUT"

export const OPEN_ALERT = "OPEN_ALERT"
export const CLOSE_ALERT = "CLOSE_ALERT"

export const DASHBOARD_LOADING = "DASHBOARD_LOADING"
export const DASHBOARD_DATA = "DASHBOARD_DATA"
export const DASHBOARD_ERROR = "DASHBOARD_ERROR"


export const ALL_ORDERS_LOADING = "ALL_ORDERS_LOADING"
export const ALL_ORDERS_DATA = "ALL_ORDERS_DATA"
export const ALL_ORDERS_ERROR = "ALL_ORDERS_ERROR"