export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGOUT = "USER_LOGOUT"

export const UPDATE_CART = "UPDATE_CART"
export const ADD_OR_UPDATE_ITEM = "ADD_OR_UPDATE_ITEM"
export const REMOVE_SINGLE_ITEM = "REMOVE_SINGLE_ITEM"