export const AUTH_SET_USER = "AUTH_SET_USER";
export const AUTH_SET_ID_TOKEN = "AUTH_SET_ID_TOKEN";
export const AUTH_SET_LOADING = "AUTH_SET_LOADING";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const UPDATE_CART = "UPDATE_CART";
export const ADD_OR_UPDATE_ITEM = "ADD_OR_UPDATE_ITEM";
export const REMOVE_SINGLE_ITEM = "REMOVE_SINGLE_ITEM";

export const ORDERS_DATA_REQUEST = "ORDERS_DATA_REQUEST";
export const ORDERS_DATA_SUCCESS = "ORDERS_DATA_SUCCESS";
export const ORDERS_DATA_ERROR = "ORDERS_DATA_ERROR";
